/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package example.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Book extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 939709031782685424L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Book\",\"namespace\":\"example.avro\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"isbn\",\"type\":\"string\"},{\"name\":\"someId\",\"type\":\"int\"},{\"name\":\"author\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Book> ENCODER =
      new BinaryMessageEncoder<Book>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Book> DECODER =
      new BinaryMessageDecoder<Book>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Book> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Book> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Book> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Book>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Book to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Book from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Book instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Book fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence name;
  private java.lang.CharSequence isbn;
  private int someId;
  private java.lang.CharSequence author;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Book() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param isbn The new value for isbn
   * @param someId The new value for someId
   * @param author The new value for author
   */
  public Book(java.lang.CharSequence name, java.lang.CharSequence isbn, java.lang.Integer someId, java.lang.CharSequence author) {
    this.name = name;
    this.isbn = isbn;
    this.someId = someId;
    this.author = author;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return isbn;
    case 2: return someId;
    case 3: return author;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: isbn = (java.lang.CharSequence)value$; break;
    case 2: someId = (java.lang.Integer)value$; break;
    case 3: author = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'isbn' field.
   * @return The value of the 'isbn' field.
   */
  public java.lang.CharSequence getIsbn() {
    return isbn;
  }


  /**
   * Sets the value of the 'isbn' field.
   * @param value the value to set.
   */
  public void setIsbn(java.lang.CharSequence value) {
    this.isbn = value;
  }

  /**
   * Gets the value of the 'someId' field.
   * @return The value of the 'someId' field.
   */
  public int getSomeId() {
    return someId;
  }


  /**
   * Sets the value of the 'someId' field.
   * @param value the value to set.
   */
  public void setSomeId(int value) {
    this.someId = value;
  }

  /**
   * Gets the value of the 'author' field.
   * @return The value of the 'author' field.
   */
  public java.lang.CharSequence getAuthor() {
    return author;
  }


  /**
   * Sets the value of the 'author' field.
   * @param value the value to set.
   */
  public void setAuthor(java.lang.CharSequence value) {
    this.author = value;
  }

  /**
   * Creates a new Book RecordBuilder.
   * @return A new Book RecordBuilder
   */
  public static example.avro.Book.Builder newBuilder() {
    return new example.avro.Book.Builder();
  }

  /**
   * Creates a new Book RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Book RecordBuilder
   */
  public static example.avro.Book.Builder newBuilder(example.avro.Book.Builder other) {
    if (other == null) {
      return new example.avro.Book.Builder();
    } else {
      return new example.avro.Book.Builder(other);
    }
  }

  /**
   * Creates a new Book RecordBuilder by copying an existing Book instance.
   * @param other The existing instance to copy.
   * @return A new Book RecordBuilder
   */
  public static example.avro.Book.Builder newBuilder(example.avro.Book other) {
    if (other == null) {
      return new example.avro.Book.Builder();
    } else {
      return new example.avro.Book.Builder(other);
    }
  }

  /**
   * RecordBuilder for Book instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Book>
    implements org.apache.avro.data.RecordBuilder<Book> {

    private java.lang.CharSequence name;
    private java.lang.CharSequence isbn;
    private int someId;
    private java.lang.CharSequence author;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(example.avro.Book.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.isbn)) {
        this.isbn = data().deepCopy(fields()[1].schema(), other.isbn);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.someId)) {
        this.someId = data().deepCopy(fields()[2].schema(), other.someId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.author)) {
        this.author = data().deepCopy(fields()[3].schema(), other.author);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing Book instance
     * @param other The existing instance to copy.
     */
    private Builder(example.avro.Book other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.isbn)) {
        this.isbn = data().deepCopy(fields()[1].schema(), other.isbn);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.someId)) {
        this.someId = data().deepCopy(fields()[2].schema(), other.someId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.author)) {
        this.author = data().deepCopy(fields()[3].schema(), other.author);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public example.avro.Book.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public example.avro.Book.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'isbn' field.
      * @return The value.
      */
    public java.lang.CharSequence getIsbn() {
      return isbn;
    }


    /**
      * Sets the value of the 'isbn' field.
      * @param value The value of 'isbn'.
      * @return This builder.
      */
    public example.avro.Book.Builder setIsbn(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.isbn = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'isbn' field has been set.
      * @return True if the 'isbn' field has been set, false otherwise.
      */
    public boolean hasIsbn() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'isbn' field.
      * @return This builder.
      */
    public example.avro.Book.Builder clearIsbn() {
      isbn = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'someId' field.
      * @return The value.
      */
    public int getSomeId() {
      return someId;
    }


    /**
      * Sets the value of the 'someId' field.
      * @param value The value of 'someId'.
      * @return This builder.
      */
    public example.avro.Book.Builder setSomeId(int value) {
      validate(fields()[2], value);
      this.someId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'someId' field has been set.
      * @return True if the 'someId' field has been set, false otherwise.
      */
    public boolean hasSomeId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'someId' field.
      * @return This builder.
      */
    public example.avro.Book.Builder clearSomeId() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'author' field.
      * @return The value.
      */
    public java.lang.CharSequence getAuthor() {
      return author;
    }


    /**
      * Sets the value of the 'author' field.
      * @param value The value of 'author'.
      * @return This builder.
      */
    public example.avro.Book.Builder setAuthor(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.author = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'author' field has been set.
      * @return True if the 'author' field has been set, false otherwise.
      */
    public boolean hasAuthor() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'author' field.
      * @return This builder.
      */
    public example.avro.Book.Builder clearAuthor() {
      author = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Book build() {
      try {
        Book record = new Book();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.isbn = fieldSetFlags()[1] ? this.isbn : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.someId = fieldSetFlags()[2] ? this.someId : (java.lang.Integer) defaultValue(fields()[2]);
        record.author = fieldSetFlags()[3] ? this.author : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Book>
    WRITER$ = (org.apache.avro.io.DatumWriter<Book>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Book>
    READER$ = (org.apache.avro.io.DatumReader<Book>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.name);

    out.writeString(this.isbn);

    out.writeInt(this.someId);

    if (this.author == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.author);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);

      this.isbn = in.readString(this.isbn instanceof Utf8 ? (Utf8)this.isbn : null);

      this.someId = in.readInt();

      if (in.readIndex() != 1) {
        in.readNull();
        this.author = null;
      } else {
        this.author = in.readString(this.author instanceof Utf8 ? (Utf8)this.author : null);
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          break;

        case 1:
          this.isbn = in.readString(this.isbn instanceof Utf8 ? (Utf8)this.isbn : null);
          break;

        case 2:
          this.someId = in.readInt();
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.author = null;
          } else {
            this.author = in.readString(this.author instanceof Utf8 ? (Utf8)this.author : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










